# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced0eda448d3ec50d50c1b2eaba2f2899d40963c6e41ca56773b5ab32ac0e4a57c8daa84c4690bc7f7208f304a22589dd18f69eb813dd521c718746030193c81

test:
  secret_key_base: 3b6e6647b1b22eac30ef6639c9d9c9ce91096d1b03723c8fb55f426cdeb6f2e530977a2f67b6c631fc195cf3c859914e0fe612cc428dae197f902e82df17d389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
